### ISSUE TITLE
Crashes/Hanging in 278

### ISSUE THREAD

**Issue by nimriye** [BeipDev/BeipMU#56] opened 2019-01-18 06:31 UTC
Hiya, been running v278 for a while now and experienced some odd crashes yesterday. Of course once I loaded DebugDiag as you showed me last time to try to log what was going on, then the outright crashes stopped. But I would still get odd hanging behavior when opening a log or switching windows, and this hanging behavior would create crash dumps in DebugDiag.

I attached copies of the logs it made as well as the DMP file. These were created when I opened a log, and the program hung on log creation for several seconds. Hopefully these indicate something of what might be happening overall. Thank you for reading!

**Comment by BeipDev** [comment] 2019-01-18 06:41
I opened up the hang in the debugger. Are you trying to log to a webdav folder? I see it hanging in the OS code to choose a folder. Are you on Discord? Just asking since then I could discuss it faster.

Also, you might not want to post your dump file here just in case it holds any personal data in the crash dump (This dump is a tiny 179K, so just some callstack data, but I'm paranoid about that stuff).

**Comment by nimriye** [comment] 2019-01-18 19:42
Oh true! I looked through the logs and the dump file before putting up and didn't see anything, but I'll remove again in case anything was hidden.

Hmmm, I'm not sure on the webdav folder. I don't think so? I log to a folders in the regular Documents folder C:\Users\USER\Documents\. But I am on Discord! I really should get on the Beip one and keep forgetting.

**Comment by BeipDev** [comment] 2019-01-26 05:48
Closing this bug since it was not a bug in BeipMU (or at least it didn't look like it was). Hopefully we find the crash cause in the future

**Closed by BeipDev** 2019-01-26 05:48 UTC
