### ISSUE TITLE
Crash with 276, Input Box Text

### ISSUE THREAD

**Issue by nimriye** [BeipDev/BeipMU#42] opened 2018-12-16 20:01 UTC
Hiya, trying out version 276 for the split-screen functionality which is very nice! I've run into an issue with the program, however, where setting sound triggers still seems to be related to inflated memory usage and an eventual crash (similar to https://github.com/BeipDev/BeipMU/issues/22).

Running the program without using any sound triggers keeps it steady at about 5-7 MB of memory usage -- however with the sound triggers I have, which are set to play a .wav file once when the window does not have focus, the usage goes up to about 25 MB, with a memory spike when a sound is played. I've just turned off my triggers for now, but thought I would report.

Another issue which seems to be persisting is certain fonts not rendering correctly in the input box. They render fine in the output window, but in the input box they look like this:

![beipbug](https://user-images.githubusercontent.com/40511921/50058180-9c1b1280-0142-11e9-8b4c-401755c36ef0.jpg)

Thank you for all the time you put into this program!

**Comment by BeipDev** [comment] 2018-12-16 20:30
Yeah, the sound issue was fixed on Microsoft's side months ago, but it wasn't until just a week or two ago that the fix finally rolled out to my pc. The memory usage stays constant as of 'Version 1809 (OS Build 17763.168)' for me. What build are you on?

Glad you like the split screen!

What fonts do the weird height? I haven't ever seen that, is there any pattern to it?

**Comment by nimriye** [comment] 2018-12-16 20:48
Man, I'm on Version 1803. The fix must not have come out to me yet. I'll keep an eye out for how to get ahold of it.

The font I'm using which results in the strange height is Monaco. It's not a standard Windows font which might be the reason why, though it's odd it would work fine in the output box and not the input box.

**Comment by BeipDev** [comment] 2018-12-16 23:30
I manually checked for windows updates and got it.

Do any built in fonts have that issue? That way I can easily try it.

**Comment by nimriye** [comment] 2018-12-17 01:43
There it goes! I'd just done an update this morning so not sure why it didn't offer me 1809 update then :| I'll try updating and see if that improves the sound performance.

As for the fonts... trying to find a built-in Windows font that does this, but none appear to. I think it might be a flaw of the custom fonts themselves, which is sad. But thank you for your responses!

**Comment by BeipDev** [comment] 2018-12-17 05:45
I have some code that figures out the height for that window, so I can probably fix it if I have the font. Do you have a link where I can get the font?

**Comment by nimriye** [comment] 2018-12-17 07:39
Oh, it would be amazing if you could! The font is from here http://www.gringod.com/wp-upload/software/Fonts/Monaco_5.1.ttf.

If that direct download doesn't work for some reason, it was linked in this page http://www.gringod.com/2006/11/01/new-version-of-monaco-font/.

**Comment by BeipDev** [comment] 2018-12-18 05:39
I tried the font but it worked just fine. Is there something I'm missing? The first link worked, though it downloaded as a .man file I just renamed it to .ttf and it worked fine. It's 185KB

**Comment by nimriye** [comment] 2018-12-18 07:08
Yeah, I'm really baffled what was going on with my system. I asked a friend to send me her copy of the same font, and it worked. My system must have been stuck on a corrupted version somehow, despite me deleting and reinstalling the font multiple times.

Thanks so much for helping to troubleshoot, either way. While doing this I did notice some crashes with the program, but I suspect it might be related to the old init_js startup script which used to come with Beip and which I was still loading. I disabled it for now, if I observe any other odd behavior I will drop back!

**Comment by BeipDev** [comment] 2018-12-18 07:12
Haha, glad I could help! Strange that it was only my window and not the OS one.

I'm still using the "old" init_js script but it's working fine, do you know how to repro the crash?

**Comment by nimriye** [comment] 2018-12-18 14:36
Yeah, it's strange. I think it might be RichEdit having a strange interaction with this font in particular that makes it unreliable (since I only start seeing the problem after v257), so I might still switch off it to a font actually made for Windows.

As far as the crash, it's very hard to reproduce reliably and I've just been experimenting to try to isolate what it might be. I still crashed with disabled sound triggers and a script loaded, so I don't think it's the sound triggers; now trying it without triggers OR script, and it hasn't crashed quite yet.

The one thing I WAS doing every time the crash happened was, I was trying to switch between open tabs/worlds. Either by using the forward/back buttons on my mouse, or just clicking to switch tabs. I wonder if it might be related to https://github.com/BeipDev/BeipMU/issues/36. Will keep testing things out either way.

**Comment by BeipDev** [comment] 2018-12-19 02:00
For the crash, if you can give me a mini dump of the crash then I could probably figure out what the problem is. That way it just needs to happen once, but you need some steps to capture a mini dump properly. Or if you use the store version and don't have all telemetry disabled I'll get a call stack for the crash.

It'd be nice if it was related to #36, since then it'd fix them both!

**Comment by nimriye** [comment] 2018-12-19 05:04
I could try to get a minidump of a crash if I run into one again! Not sure how to take one, but if you let me know the steps, I can try to take them. I just use the downloadable zip and not the store version.

**Comment by BeipDev** [comment] 2018-12-19 05:35
Hmm, this isn't the easiest to follow but here are some instructions on how to get a minidump from a crash: https://blogs.msdn.microsoft.com/chaun/2013/11/12/steps-to-catch-a-simple-crash-dump-of-a-crashing-process/

If you have visual studio or any other debugger I can give you a link to the PDB files so you could catch the crash yourself. Up to how technical you want to get!

**Comment by nimriye** [comment] 2018-12-19 14:55
Oh awesome! I'll try to set up Debugdiag to catch any future crashes. None yet so far.

On a tangent is there a way to keybind the 'convert returns to %r' functionality? I was looking for a way to do so but couldn't find it. Thanks for tanking my questions!

**Comment by BeipDev** [comment] 2018-12-19 20:12
Cool, hopefully we can catch the crash in action and fix it! Just be sure to log a mini dump (callstack related info only), as a full dump has the entire process memory and I don't want that much info!

If you want a keybinding feel free to log an issue with a suggested key binding for it! If it's not in the current list then there isn't a way.

**Comment by nimriye** [comment] 2018-12-19 21:00
OK got it. Hopefully it doesn't crash again at all, I cleaned up the script I was using in case there was something bad in there.

And cool, I wasn't sure if there was a way to add it myself that I was missing. I will log a separate ticket so that we can close this one for now. Thanks again.

**Comment by BeipDev** [comment] 2018-12-19 21:09
Cool, closing for now!

**Closed by BeipDev** 2018-12-19 21:09 UTC
